### ISSUE TITLE
code mirror requirement conflicts with flask-cms

### ISSUE THREAD

**Issue by cstrutton** [jstacoder/flask-xxl#9]
flask-xxl requires code-mirror == 0.0.3
flask-cms (which requires flask-xxl) requires code-mirror == 0.0.4

**Comment by jstacoder** [comment]
im not sure whats changed so for now im going to stick to 0.0.3, flask_cms was failing because there was no version requirement so it installed the latest 0.0.4 while flask-xxl wanted 0.0.3, so i updated flask-cms to specifically look for 0.0.3 as well.
